export const INITIAL_VALUES_KONTRAK = {
  karyawan_nip: '',
  nonik: '',
  unit_id: '',
  tempat_tugas_id: '',
  jabatan_id: '',
  gaji: '',
  karyawan_name: '',
  tempat_lahir: '',
  tanggal_lahir: '',
  tgl_masuk_kerja: '',
  tgl_habis_kontrak: '',
  kontrak_kode: '',
  request_no: '',
  request_date: '',
  kontrak_id: '',
  uang_makan: '',
  tunjangan: '',
  tunjangan_komunikasi: '',
  tunjangan_khusus: '',
  tunjangan_variable: ''
};
