// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

export const SET_LOADING_SUBMIT_BUTTON = 'SET_LOADING_SUBMIT_BUTTON';

export const GET_KARYAWAN_LIST = 'GET_KARYAWAN_LIST';
export const SET_LOADING_KARYAWAN_LIST = 'SET_LOADING_KARYAWAN_LIST';
export const GET_KARYAWAN_DETAIL = 'GET_KARYAWAN_DETAIL';
export const SET_LOADING_KARYAWAN_DETAIL = 'SET_LOADING_KARYAWAN_DETAIL';

export const GET_MASTER_BANK = 'GET_MASTER_BANK';
export const SET_LOADING_MASTER_BANK_LIST = 'SET_LOADING_MASTER_BANK_LIST';

export const GET_MASTER_IURAN = 'GET_MASTER_IURAN';
export const SET_LOADING_MASTER_IURAN_LIST = 'SET_LOADING_MASTER_IURAN_LIST';

export const GET_MASTER_JABATAN = 'GET_MASTER_JABATAN';
export const SET_LOADING_MASTER_JABATAN_LIST = 'SET_LOADING_MASTER_JABATAN_LIST';

export const GET_MASTER_PAJAK = 'GET_MASTER_PAJAK';
export const SET_LOADING_MASTER_PAJAK_LIST = 'SET_LOADING_MASTER_PAJAK_LIST';

export const GET_MASTER_TEMPAT_TUGAS = 'GET_MASTER_TEMPAT_TUGAS';
export const SET_LOADING_MASTER_TEMPAT_TUGAS = 'SET_LOADING_MASTER_TEMPAT_TUGAS';

export const GET_MASTER_UNIT_BISNIS = 'GET_MASTER_UNIT_BISNIS';
export const SET_LOADING_MASTER_UNIT_BISNIS = 'SET_LOADING_MASTER_UNIT_BISNIS';

export const GET_DROPDOWN_JABATAN = 'GET_DROPDOWN_JABATAN';
export const GET_DROPDOWN_UNIT_BISNIS = 'GET_DROPDOWN_UNIT_BISNIS';
export const GET_DROPDOWN_TEMPAT_TUGAS = 'GET_DROPDOWN_TEMPAT_TUGAS';
