// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

export const SET_LOADING_SUBMIT_BUTTON = 'SET_LOADING_SUBMIT_BUTTON';

export const GET_KARYAWAN_LIST = 'GET_KARYAWAN_LIST';
export const SET_LOADING_KARYAWAN_LIST = 'SET_LOADING_KARYAWAN_LIST';
export const GET_KARYAWAN_DETAIL = 'GET_KARYAWAN_DETAIL';
export const SET_LOADING_KARYAWAN_DETAIL = 'SET_LOADING_KARYAWAN_DETAIL';
export const GET_KARYAWAN_BY_NIP = 'GET_KARYAWAN_BY_NIP';
export const SET_LOADING_KARYAWAN_BY_NIP = 'SET_LOADING_KARYAWAN_BY_NIP';
export const SET_LOADING_STOP_KARYAWAN = 'SET_LOADING_STOP_KARYAWAN';

export const GET_KONTRAK_LIST = 'GET_KONTRAK_LIST';
export const SET_LOADING_KONTRAK_LIST = 'SET_LOADING_KONTRAK_LIST';
export const GET_KONTRAK_DETAIL = 'GET_KONTRAK_DETAIL';
export const SET_LOADING_KONTRAK_DETAIL = 'SET_LOADING_KONTRAK_DETAIL';
export const SET_LOADING_KONTRAK_BY_NIP = 'SET_LOADING_KONTRAK_BY_NIP';
export const GET_KONTRAK_LIST_BY_NIP = 'GET_KONTRAK_LIST_BY_NIP';
export const SET_LOADING_LIST_KONTRAK_BY_NIP = 'SET_LOADING_LIST_KONTRAK_BY_NIP';
export const SET_LOADING_STOP_KONTRAK = 'SET_LOADING_STOP_KONTRAK';

export const GET_MASTER_BANK = 'GET_MASTER_BANK';
export const SET_LOADING_MASTER_BANK_LIST = 'SET_LOADING_MASTER_BANK_LIST';

export const GET_MASTER_IURAN = 'GET_MASTER_IURAN';
export const SET_LOADING_MASTER_IURAN_LIST = 'SET_LOADING_MASTER_IURAN_LIST';

export const GET_MASTER_JABATAN = 'GET_MASTER_JABATAN';
export const SET_LOADING_MASTER_JABATAN_LIST = 'SET_LOADING_MASTER_JABATAN_LIST';

export const GET_MASTER_PAJAK = 'GET_MASTER_PAJAK';
export const SET_LOADING_MASTER_PAJAK_LIST = 'SET_LOADING_MASTER_PAJAK_LIST';

export const GET_MASTER_TEMPAT_TUGAS = 'GET_MASTER_TEMPAT_TUGAS';
export const SET_LOADING_MASTER_TEMPAT_TUGAS = 'SET_LOADING_MASTER_TEMPAT_TUGAS';

export const GET_MASTER_UNIT_BISNIS = 'GET_MASTER_UNIT_BISNIS';
export const SET_LOADING_MASTER_UNIT_BISNIS = 'SET_LOADING_MASTER_UNIT_BISNIS';

export const GET_DROPDOWN_JABATAN = 'GET_DROPDOWN_JABATAN';
export const GET_DROPDOWN_UNIT_BISNIS = 'GET_DROPDOWN_UNIT_BISNIS';
export const GET_DROPDOWN_TEMPAT_TUGAS = 'GET_DROPDOWN_TEMPAT_TUGAS';
export const GET_DROPDOWN_BANK = 'GET_DROPDOWN_BANK';

export const GET_REPORT_TAGIHAN_GAJI = 'GET_REPORT_TAGIHAN_GAJI';
export const SET_LOADING_REPORT_TAGIHAN_GAJI = 'SET_LOADING_REPORT_TAGIHAN_GAJI';
export const GET_REPORT_ALL_TAGIHAN_GAJI = 'GET_REPORT_ALL_TAGIHAN_GAJI';
export const SET_LOADING_REPORT_ALL_TAGIHAN_GAJI = 'SET_LOADING_REPORT_ALL_TAGIHAN_GAJI';

export const GET_GENERATE_SLIP_GAJI = 'GET_GENERATE_SLIP_GAJI';
export const SET_LOADING_GENERATE_SLIP_GAJI = 'SET_LOADING_GENERATE_SLIP_GAJI';

export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const SET_LOADING_DASHBOARD_DATA = 'SET_LOADING_DASHBOARD_DATA';
